export const FETCH_PLUGINS_START = 'FETCH__PLUGINS_START';
export const FETCH_PLUGINS_SUCCESS = 'FETCH__PLUGINS_SUCCESS';
export const FETCH_PLUGINS_FAILURE = 'FETCH__PLUGINS_FAILURE';
export const FETCH_PLUGINS_CLEAR = 'FETCH__PLUGINS_CLEAR';