export const FETCH_TABDATA_START = 'FETCH__TABDATA_START';
export const FETCH_TABDATA_SUCCESS = 'FETCH__TABDATA_SUCCESS';
export const FETCH_TABDATA_FAILURE = 'FETCH__TABDATA_FAILURE';
export const FETCH_TABDATA_CLEAR = 'FETCH__TABDATA_CLEAR';