export const UPDATE_TABDATA_START = 'UPDATE__TABDATA_START';
export const UPDATE_TABDATA_SUCCESS = 'UPDATE__TABDATA_SUCCESS';
export const UPDATE_TABDATA_FAILURE = 'UPDATE__TABDATA_FAILURE';
export const UPDATE_TABDATA_CLEAR = 'UPDATE__TABDATA_CLEAR';